[package]
name = "rust-poly"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
num-traits = "0.2.15"

[dev-dependencies]
ndarray = "0.15.6"
