[package]
name = "api2"
version = "0.1.0"
edition = "2024"

[dependencies]
fastrand = "2.3.0"
num-complex = "0.4.6"
num-traits = "0.2.19"
thiserror = "2.0.16"

[dev-dependencies]
plotly = { version = "0.13.5", features = ["kaleido"] }
